name: s5_practice
description: S5 Practice Exam Questions

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  timer_builder: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.3

flutter:
  uses-material-design: true

  assets:
    - assets/questions.json
    - assets/images/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/S5_practice.png"
  adaptive_icon_background: "#197CD7"
  adaptive_icon_foreground: "assets/icons/S5_practice_front.png"
